config/routes.rb
Rails.application.routes.draw do

  resources :uploads, :except => [:update]

  root 'uploads#index'

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  mount_uploader :file, FileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @uploads = Upload.all
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(title: params[:title], file: params[:file])
    @upload.save
  end

  def destroy
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fairy Files</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uploads/destroy.html.erb
<h1>Uploads#destroy</h1>
<p>Find me in app/views/uploads/destroy.html.erb</p>

app/views/uploads/index.html.slim
h1 List of files
br
br
= link_to "add new files", new_upload_path
br
- @uploads.each do |u|
  = u.file.identifier
  br

app/views/uploads/new.html.slim
h1 Upload your files

br

= simple_form_for @upload, :html=>{:multipart => true } do |f|
  = f.label :title
  = f.text_field :title, required: true
  = f.label :file
  = f.file_field :file, required: true
  = f.submit

br
= link_to "Home", root_path

javascript:
  $(function() {
    $("#new_upload").plupload({
      runtimes : 'html5,flash,silverlight,html4',
      url : '#{uploads_path}',
      max_file_size : '8mb',
      chunk_size: '1mb',
      rename: true,
      sortable: true,
      dragdrop: true,
      views: {
        list: true,
        thumbs: true,
        active: 'thumbs'
      },
      multipart_params: {
        '#{request_forgery_protection_token}': '#{form_authenticity_token}',
        '#{Rails.application.config.session_options[:key]}': '#{request.session_options[:id]}'
      },
      flash_swf_url : '/plupload/js/Moxie.swf',
      silverlight_xap_url : '/plupload/js/Moxie.xap',
      init: {
        FilesAdded: function(up, files) {
          alert('Selected files: ' + files.length);
        }
      }
    });
  });

app/views/uploads/show.html.erb
<h1>Uploads#show</h1>
<p>Find me in app/views/uploads/show.html.erb</p>